obj=E02 E03 E04 E05 E06 E07 E08 E10 E11
E01: E01.c $(obj)
	cc -o E01 E01.c
E02: E02.c
	cc -o E02 E02.c
E03: E03.c calculator.h stack.c getch.c
	cc -o E03 E03.c calculator.h stack.c getch.c
E04: E04.c calculator.h stack.c getch.c
	cc -o E04 E04.c calculator.h stack.c getch.c
E05: E05.c calculator.h stack.c getch.c
	cc -o E05 E05.c calculator.h stack.c getch.c
E06: E06.c calculator.h stack.c getch.c
	cc -o E06 E06.c calculator.h stack.c getch.c
E07: E07.c calculator.h stack.c getch.c
	cc -o E07 E07.c calculator.h stack.c getch.c
E08: E08.c calculator.h stack.c getch.c
	cc -o E08 E08.c calculator.h stack.c getch.c
E10: E10.c calculator.h stack.c getch.c
	cc -o E10 E10.c calculator.h stack.c getch.c
E11: E11.c calculator.h stack.c getch.c
	cc -o E11 E11.c calculator.h stack.c getch.c
clean:
	rm E01 $(obj)
clear:
	rm *.exe
