E01: E01.c E02 E03 E04 E05 E06
	cc -o E01 E01.c
E02: GetLine.h GetLine.c E02.c
	cc -o E02 GetLine.h GetLine.c E02.c
E03: E03.c
	cc -o E03 GetLine.h GetLine.c E03.c
E04: E04.c
	cc -o E04 E04.c
E05: E05.c
	cc -o E05 E05.c
E06: E06.c
	cc -o E06 E06.c

clean:
	rm E01 E02 E03 E04 E05 E06
